### ISSUE TITLE
ArgumentError: wrong number of arguments (given 1, expected 0) - rake neo4j:migrate & rake neoj4:schema:dump

### ISSUE THREAD

**Issue by ErikVanNorstrand** [neo4jrb/neo4j-rake_tasks#41]
ArgumentError: wrong number of arguments (given 1, expected 0) - rake neo4j:migrate & rake neoj4:schema:dump

Additional information which could be helpful if relevent to your issue:

Error happens on line 47 of migration.rake "check_neo4j_version3".

### Runtime information:

Neo4j database version: 3.1.2
neo4j gem version: 9.0.7
neo4j-core gem version: 8.0.3

**Comment by cheerfulstoic** [comment]
Hey @ErikVanNorstrand This should be fixed in `neo4j-core` version 8.0.3, so hopefully a `bundle update neo4j-core` should fix it.

A couple of other clarifications:

 * Also, the `neo4j:migrate` rake task should (I believe) automagically run `neo4j:schema:dump` when it's done
 * The `neo4j:migrate` and `neo4j:schema*` tasks are actually defined in the `neo4j` gem.  I know it's probably confusion, but this gem is just for the rake tasks that allow you to install/start/stop/restart/etc... Neo4j using `rake` tasks (though now that the Neo4j Desktop app is out, that's becoming a better way to manage Neo4j servers for dev / test IMO)

**Comment by cheerfulstoic** [comment]
(Make sure you're on 8.0.4, by the way.  There's another fix related to this)

**Comment by cheerfulstoic** [comment]
Ah, I see you're on 8.0.3.  I still think 8.0.4 will fix the issue, but please let me know if not.  Are you using HTTP or Bolt?

**Comment by ErikVanNorstrand** [comment]
Resolved in 8.0.4!

**Comment by cheerfulstoic** [comment]
🎉
